[2025-10-29T20:11:02.371+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag2_kafka_elastic_gcs.ConsumeKafka scheduled__2025-10-29T20:10:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
