[2025-10-28T23:31:01.179+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2_elastic_gcs_ingestion.ConsumKafkaResult scheduled__2025-10-28T23:30:00+00:00 [queued]>
[2025-10-28T23:31:01.188+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2_elastic_gcs_ingestion.ConsumKafkaResult scheduled__2025-10-28T23:30:00+00:00 [queued]>
[2025-10-28T23:31:01.189+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-28T23:31:01.207+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ConsumKafkaResult> on 2025-10-28 23:30:00+00:00
[2025-10-28T23:31:01.216+0000] {standard_task_runner.py:60} INFO - Started process 204 to run task
[2025-10-28T23:31:01.252+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag2_elastic_gcs_ingestion', 'ConsumKafkaResult', 'scheduled__2025-10-28T23:30:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag2_elastic_gcs_ingestion.py', '--cfg-path', '/tmp/tmpa_1eaayp']
[2025-10-28T23:31:01.261+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask ConsumKafkaResult
[2025-10-28T23:31:01.386+0000] {task_command.py:423} INFO - Running <TaskInstance: dag2_elastic_gcs_ingestion.ConsumKafkaResult scheduled__2025-10-28T23:30:00+00:00 [running]> on host 62eef3cae3a1
[2025-10-28T23:31:01.558+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2_elastic_gcs_ingestion' AIRFLOW_CTX_TASK_ID='ConsumKafkaResult' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-28T23:30:00+00:00'
[2025-10-28T23:31:05.399+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-10-28T23:31:05.400+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
[2025-10-28T23:31:05.401+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-10-28T23:31:05.402+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag2_elastic_gcs_ingestion.py", line 40, in consume_from_kafka_result
    consumer = get_kafka_consumer('result')
  File "/opt/airflow/dags/dag2_elastic_gcs_ingestion.py", line 19, in get_kafka_consumer
    return KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-10-28T23:31:05.415+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag2_elastic_gcs_ingestion, task_id=ConsumKafkaResult, execution_date=20251028T233000, start_date=20251028T233101, end_date=20251028T233105
[2025-10-28T23:31:05.427+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task ConsumKafkaResult (NoBrokersAvailable; 204)
[2025-10-28T23:31:05.442+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-28T23:31:05.466+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
