[2025-10-29T14:39:03.981+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2_kafka_elastic_gcs.PutElasticSearch scheduled__2025-10-29T14:38:00+00:00 [queued]>
[2025-10-29T14:39:03.989+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2_kafka_elastic_gcs.PutElasticSearch scheduled__2025-10-29T14:38:00+00:00 [queued]>
[2025-10-29T14:39:03.990+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-29T14:39:04.000+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): PutElasticSearch> on 2025-10-29 14:38:00+00:00
[2025-10-29T14:39:04.008+0000] {standard_task_runner.py:60} INFO - Started process 715 to run task
[2025-10-29T14:39:04.011+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag2_kafka_elastic_gcs', 'PutElasticSearch', 'scheduled__2025-10-29T14:38:00+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/dag2_elastic_gcs_ingestion.py', '--cfg-path', '/tmp/tmptrljsb8k']
[2025-10-29T14:39:04.014+0000] {standard_task_runner.py:88} INFO - Job 391: Subtask PutElasticSearch
[2025-10-29T14:39:04.072+0000] {task_command.py:423} INFO - Running <TaskInstance: dag2_kafka_elastic_gcs.PutElasticSearch scheduled__2025-10-29T14:38:00+00:00 [running]> on host c91e5c2c38a7
[2025-10-29T14:39:04.165+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2_kafka_elastic_gcs' AIRFLOW_CTX_TASK_ID='PutElasticSearch' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T14:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T14:38:00+00:00'
[2025-10-29T14:39:04.172+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/operators/python.py:216 AirflowProviderDeprecationWarning: This class is deprecated.
            Please use `***.providers.elasticsearch.hooks.elasticsearch.ElasticsearchSQLHook`.
[2025-10-29T14:39:04.182+0000] {base.py:83} INFO - Using connection ID 'elasticsearch_default' for task execution.
[2025-10-29T14:39:04.188+0000] {_transport.py:358} INFO - HEAD http://localhost:9200/taxi_rides [status:N/A duration:0.003s]
[2025-10-29T14:39:04.188+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(http://localhost:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2025-10-29T14:39:04.189+0000] {_transport.py:395} WARNING - Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7d72bbc10190>: Failed to establish a new connection: [Errno 111] Connection refused)
[2025-10-29T14:39:04.191+0000] {_transport.py:358} INFO - HEAD http://localhost:9200/taxi_rides [status:N/A duration:0.000s]
[2025-10-29T14:39:04.191+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(http://localhost:9200)> has failed for 2 times in a row, putting on 2 second timeout
[2025-10-29T14:39:04.192+0000] {_transport.py:395} WARNING - Retrying request after failure (attempt 1 of 3)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7d72bbc10340>: Failed to establish a new connection: [Errno 111] Connection refused)
[2025-10-29T14:39:04.193+0000] {_transport.py:358} INFO - HEAD http://localhost:9200/taxi_rides [status:N/A duration:0.001s]
[2025-10-29T14:39:04.193+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(http://localhost:9200)> has failed for 3 times in a row, putting on 4 second timeout
[2025-10-29T14:39:04.194+0000] {_transport.py:395} WARNING - Retrying request after failure (attempt 2 of 3)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7d72bbc10580>: Failed to establish a new connection: [Errno 111] Connection refused)
[2025-10-29T14:39:04.195+0000] {_transport.py:358} INFO - HEAD http://localhost:9200/taxi_rides [status:N/A duration:0.000s]
[2025-10-29T14:39:04.195+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(http://localhost:9200)> has failed for 4 times in a row, putting on 8 second timeout
[2025-10-29T14:39:04.195+0000] {dag2_elastic_gcs_ingestion.py:120} ERROR - ❌ Erreur d’insertion Elasticsearch : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7d72bbc10190>: Failed to establish a new connection: [Errno 111] Connection refused))
[2025-10-29T14:39:04.195+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-29T14:39:04.205+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag2_kafka_elastic_gcs, task_id=PutElasticSearch, execution_date=20251029T143800, start_date=20251029T143903, end_date=20251029T143904
[2025-10-29T14:39:04.265+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-29T14:39:04.284+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
