[2025-10-28T22:56:00.942+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T22:55:00+00:00 [queued]>
[2025-10-28T22:56:00.949+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T22:55:00+00:00 [queued]>
[2025-10-28T22:56:00.950+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-28T22:56:00.965+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ConsumKafka> on 2025-10-28 22:55:00+00:00
[2025-10-28T22:56:00.973+0000] {standard_task_runner.py:60} INFO - Started process 284 to run task
[2025-10-28T22:56:00.978+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_calcul_trajet_kafka', 'ConsumKafka', 'scheduled__2025-10-28T22:55:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag1_kafka_processing.py', '--cfg-path', '/tmp/tmp3j68864x']
[2025-10-28T22:56:00.981+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask ConsumKafka
[2025-10-28T22:56:01.042+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T22:55:00+00:00 [running]> on host 66876e18f4a7
[2025-10-28T22:56:01.123+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_calcul_trajet_kafka' AIRFLOW_CTX_TASK_ID='ConsumKafka' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T22:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-28T22:55:00+00:00'
[2025-10-28T22:56:01.129+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:56:01.130+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:56:01.131+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:56:01.132+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.04 secs
[2025-10-28T22:56:01.178+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:56:01.179+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:56:01.179+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:56:01.180+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.09 secs
[2025-10-28T22:56:01.268+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:56:01.269+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:56:01.270+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:56:01.270+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.18 secs
[2025-10-28T22:56:01.453+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:56:01.454+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:56:01.454+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:56:01.455+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.47 secs
[2025-10-28T22:56:01.927+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:56:01.928+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:56:01.928+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:56:01.929+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.85 secs
[2025-10-28T22:56:02.778+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:56:02.779+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:56:02.779+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:56:02.780+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.35 secs
[2025-10-28T22:56:03.129+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag1_kafka_processing.py", line 70, in consume_from_kafka_source
    consumer = get_kafka_consumer('source')
  File "/opt/airflow/dags/dag1_kafka_processing.py", line 42, in get_kafka_consumer
    return KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-10-28T22:56:03.144+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag1_calcul_trajet_kafka, task_id=ConsumKafka, execution_date=20251028T225500, start_date=20251028T225600, end_date=20251028T225603
[2025-10-28T22:56:03.157+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task ConsumKafka (NoBrokersAvailable; 284)
[2025-10-28T22:56:03.203+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-28T22:56:03.228+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
