[2025-10-29T12:40:01.491+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag2_kafka_to_elastic.ConsumeKafkaResult scheduled__2025-10-29T12:39:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
