[2025-10-28T22:55:20.555+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T22:54:00+00:00 [queued]>
[2025-10-28T22:55:20.565+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T22:54:00+00:00 [queued]>
[2025-10-28T22:55:20.567+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-28T22:55:20.581+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ConsumKafka> on 2025-10-28 22:54:00+00:00
[2025-10-28T22:55:20.589+0000] {standard_task_runner.py:60} INFO - Started process 270 to run task
[2025-10-28T22:55:20.594+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_calcul_trajet_kafka', 'ConsumKafka', 'scheduled__2025-10-28T22:54:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag1_kafka_processing.py', '--cfg-path', '/tmp/tmpea68y5to']
[2025-10-28T22:55:20.597+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask ConsumKafka
[2025-10-28T22:55:20.663+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_calcul_trajet_kafka.ConsumKafka scheduled__2025-10-28T22:54:00+00:00 [running]> on host 66876e18f4a7
[2025-10-28T22:55:20.744+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_calcul_trajet_kafka' AIRFLOW_CTX_TASK_ID='ConsumKafka' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T22:54:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-28T22:54:00+00:00'
[2025-10-28T22:55:20.749+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:55:20.750+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:55:20.751+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:55:20.752+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.05 secs
[2025-10-28T22:55:20.799+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:55:20.800+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:55:20.800+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:55:20.801+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.11 secs
[2025-10-28T22:55:20.911+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:55:20.911+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:55:20.912+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:55:20.912+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.20 secs
[2025-10-28T22:55:21.118+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:55:21.120+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:55:21.122+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:55:21.123+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.33 secs
[2025-10-28T22:55:21.450+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:55:21.451+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:55:21.451+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:55:21.452+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.95 secs
[2025-10-28T22:55:22.408+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to kafka:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-28T22:55:22.409+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Connect attempt returned error 111. Disconnecting.
[2025-10-28T22:55:22.410+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-10-28T22:55:22.410+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.34 secs
[2025-10-28T22:55:22.748+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag1_kafka_processing.py", line 70, in consume_from_kafka_source
    consumer = get_kafka_consumer('source')
  File "/opt/airflow/dags/dag1_kafka_processing.py", line 42, in get_kafka_consumer
    return KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-10-28T22:55:22.762+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag1_calcul_trajet_kafka, task_id=ConsumKafka, execution_date=20251028T225400, start_date=20251028T225520, end_date=20251028T225522
[2025-10-28T22:55:22.775+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task ConsumKafka (NoBrokersAvailable; 270)
[2025-10-28T22:55:22.816+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-28T22:55:22.839+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
